# Generated by Django 3.1 on 2020-09-08 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'maintain'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
