# Generated by Django 3.1 on 2020-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200908_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='ghimire', max_length=100),
        ),
    ]
